import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '@/lib/api'

const number = (value, fallback = 0) => Number.isFinite(Number(value)) ? Math.max(0, Number(value)) : fallback
function storePayload(form = {}) { return { store_name: form.store_name, legal_name: form.legal_name, logo_url: form.logo_url, currency_code: form.currency_code, currency_symbol: form.currency_symbol, country_code: form.country_code, support_email: form.support_email, support_phone: form.support_phone, whatsapp_number: form.whatsapp_number ?? form.support_whatsapp, address: typeof form.address === 'object' ? form.address : { line1: form.address || '' }, social_links: form.social_links || {}, gold_scheme_enabled: form.gold_scheme_enabled ?? form.scheme_enabled ?? true, cod_enabled: form.cod_enabled ?? true, online_payment_enabled: false, bank_transfer_enabled: form.bank_transfer_enabled ?? true, cod_min_order_amount: number(form.cod_min_order_amount ?? form.cod_min_order), cod_max_order_amount: form.cod_max_order_amount === '' ? null : number(form.cod_max_order_amount ?? form.cod_max_order), minimum_order_amount: number(form.minimum_order_amount), shipping_fee: number(form.shipping_charge ?? form.flat_shipping_fee), free_shipping_threshold: number(form.free_shipping_min_amount ?? form.free_shipping_above), return_window_days: number(form.return_window_days, 7), payment_timeout_minutes: number(form.payment_timeout_minutes ?? form.pending_payment_minutes, 30) } }
function adaptStore(row) { return row ? { ...row, support_whatsapp: row.whatsapp_number || '', scheme_enabled: row.gold_scheme_enabled ?? true, cod_max_order: row.cod_max_order_amount, cod_min_order: row.cod_min_order_amount, shipping_charge: row.shipping_fee, flat_shipping_fee: row.shipping_fee, free_shipping_min_amount: row.free_shipping_threshold, free_shipping_above: row.free_shipping_threshold, pending_payment_minutes: row.payment_timeout_minutes, address: typeof row.address === 'string' ? row.address : row.address?.line1 || '' } : row }
function taxPayload(form = {}) { return { tax_name: form.tax_name || 'VAT', tax_percent: number(form.vat_percent ?? form.gst_percent ?? form.tax_percent), tax_mode: form.prices_include_vat ? 'inclusive' : form.tax_mode || 'exclusive', tax_registration_number: form.tax_registration_number ?? form.gst_number ?? form.vat_number ?? form.trn, apply_on: form.apply_on ?? form.gst_on ?? 'total', is_active: form.is_active ?? true } }
function adaptTax(row) { return row ? { ...row, vat_percent: row.tax_percent, gst_percent: row.tax_percent, gst_number: row.tax_registration_number, prices_include_vat: row.tax_mode === 'inclusive', gst_on: row.apply_on, price_inclusive: row.tax_mode === 'inclusive' } : row }
export function useTaxSettings() { return useQuery({ queryKey: ['tax-settings'], queryFn: async () => adaptTax((await api.get('/customer/catalog/bootstrap')).tax), staleTime: 600000 }) }
export function useAdminSettings() { const bootstrap = useQuery({ queryKey: ['admin-settings-bootstrap'], queryFn: () => api.get('/customer/catalog/bootstrap') }); return { store: adaptStore(bootstrap.data?.settings), tax: adaptTax(bootstrap.data?.tax), isLoading: bootstrap.isLoading } }
export function useAdminSettingsMutations() { const qc = useQueryClient(); const invalidate = () => { qc.invalidateQueries({ queryKey: ['admin-settings-bootstrap'] }); qc.invalidateQueries({ queryKey: ['store-settings'] }); qc.invalidateQueries({ queryKey: ['tax-settings'] }) }; const updateStore = useMutation({ mutationFn: (form) => api.patch('/admin/catalog/settings/store', storePayload(form)).then(adaptStore), onSuccess: invalidate }); const updateTax = useMutation({ mutationFn: (form) => api.patch('/admin/catalog/settings/tax', taxPayload(form)).then(adaptTax), onSuccess: invalidate }); return { updateStore, updateTax } }
